title: null
author:
  - {name: "David Knigge", email: "d.m.knigge@uva.nl"}
description: > # this means to ignore newlines until "show_excerpts:"
  .

future: true # show posts dated in future
show_excerpts: false # set to true to show excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-postcss
