title: Deep Thinking Hour
description: The Deep Thinking Hour is a series of talks and panel discussions on advancements in Deep Learning, hosted at the University of Amsterdam. This initiative is supported by ELLIS.
tagline: The Deep Thinking Hour is a series of talks and panel discussions on advancements in Deep Learning, hosted at the University of Amsterdam. This initiative is supported by ELLIS.
author:
  - {name: "David Knigge", email: "d.m.knigge@uva.nl"}

future: true # show posts dated in future
show_excerpts: false # set to true to show excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-postcss
