title: Deep Thinking Hour
author:
  - {name: "David Knigge", email: "d.m.knigge@uva.nl"}
description: > # this means to ignore newlines until "show_excerpts:"
  .

future: true # show posts dated in future
show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-postcss
